version: '3.8'
services:

  app:
    container_name: ${NAME}
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    depends_on: 
      - db
    volumes:
      - app-data:/home/${NB_USER}/data
      - /Users/marcnordbruch/Downloads/letsencrypt:/etc/letsencrypt
    ports:
      - "10000:8888"
    command: >
      start-notebook.sh 
      --NotebookApp.password=${JUPYTER_PASSWORD} 
      --NotebookApp.base_url=/
      --NotebookApp.ip=*
      --NotebookApp.certfile=/etc/letsencrypt/live/${LETSENCRYPT_FQDN}/fullchain.pem
      --NotebookApp.keyfile=/etc/letsencrypt/live/${LETSENCRYPT_FQDN}/privkey.pem
    user: root
    environment:
      NB_USER: ${NB_USER}
      NB_UID: 501
      NB_GID: 20
      CHOWN_HOME: "yes"
      CHOWN_HOME_OPTS: "-R"
      GRANT_SUDO: "yes"
      USE_HTTPS: "yes"
      w: /home/${NB_USER}
      
    networks: 
      - backend-network
      - frontend-network

  db:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - db-data:/data/postgres
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - backend-network

  pgadmin4:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:latest
    restart: always
    depends_on: 
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - backend-network
 
networks:
  backend-network:
  frontend-network:
 
volumes:
    app-data:
    db-data:
    pgadmin:
    secrets:
        name: ${SECRETS_VOLUME}